spring:
  application:
    name: techview

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-32-bytes-long-for-hmac-sha256-algorithm
  access-expiration: 1800000 # 30분 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

